# Generated by Django 5.2.6 on 2026-09-19 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OddSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selection', models.CharField(max_length=120)),
                ('line', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('odd', models.DecimalField(decimal_places=3, max_digits=8)),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.bookmaker')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='sports.event')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='odds.market')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'market', 'selection', '-captured_at'], name='odds_oddsna_event_i_35f003_idx')],
            },
        ),
    ]
