# Generated by Django 5.2.6 on 2026-09-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammatchstats',
            name='cards',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammatchstats',
            name='corners',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammatchstats',
            name='shots',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammatchstats',
            name='shots_on_target',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='teammatchstats',
            constraint=models.UniqueConstraint(fields=('event', 'team'), name='unique_event_team_stats'),
        ),
    ]
