# Generated by Django 5.2.6 on 2026-09-19 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_alter_teammatchstats_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('position', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='sports.team')),
            ],
        ),
        migrations.CreateModel(
            name='EventLineupPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=10)),
                ('starter', models.BooleanField(default=False)),
                ('substitute', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('captured_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_players', to='sports.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.team')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.player')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerMatchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=10)),
                ('started', models.BooleanField(default=False)),
                ('substitute', models.BooleanField(default=False)),
                ('minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('xg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('xa', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True)),
                ('shots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('shots_on_target', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saves', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('team_goals_conceded', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('clean_sheet', models.BooleanField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='sports.event')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='sports.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.team')),
            ],
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('sport', 'external_id'), name='unique_sport_player_external_id'),
        ),
        migrations.AddConstraint(
            model_name='eventlineupplayer',
            constraint=models.UniqueConstraint(fields=('event', 'player'), name='unique_event_lineup_player'),
        ),
        migrations.AddIndex(
            model_name='playermatchstats',
            index=models.Index(fields=['player', '-event'], name='sports_play_player__20ef3c_idx'),
        ),
        migrations.AddConstraint(
            model_name='playermatchstats',
            constraint=models.UniqueConstraint(fields=('event', 'player'), name='unique_event_player_stats'),
        ),
    ]
