# Generated by Django 5.2.6 on 2026-09-20 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_player_eventlineupplayer_playermatchstats_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='competition',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('sport', 'external_id'), name='unique_sport_competition_external_id'),
        ),
    ]
