# Generated by Django 5.2.6 on 2026-09-20 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_competition_unique_sport_competition_external_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='unique_event_external_id'),
        ),
    ]
